name: fazaa
description: "A new Flutter project."
publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  awesome_dialog: ^3.2.1
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: cocon-next-arabic
      fonts:
        - asset: assets/fonts/cocon-next-arabic.ttf
    - family: Hacen Beirut
      fonts:
        - asset: assets/fonts/Hacen Beirut.ttf